const readFile = require('./utils/file')

const day1 = require('./day1/')
const day2 = require('./day2/')
const day3 = require('./day3/')
const day4 = require('./day4/')
const day5 = require('./day5/')
const day6 = require('./day6/')
const day7 = require('./day7/')

console.log(day1(readFile('./day1/input.txt')))
console.log(day2(readFile('./day2/input.txt')))
console.log(day3(readFile('./day3/test.txt')))
console.log(day4(readFile('./day4/test.txt')))
console.log(day5(readFile('./day5/test.txt')), '\n---')
console.log('Day 6 (80 Days): ', day6(readFile('./day6/input.txt', true), 80))
console.log('Day 6 (256 Days): ', day6(readFile('./day6/input.txt', true), 256), '\n---')
console.log(day7(readFile('./day7/test.txt')))